### PR TITLE
fix: removing nic from dcd should not throw 404 err when running plan…

### LINKED ISSUE #467: Sync server missing primary nic returns 404 error
## Description

When synchroning the remote state of a server where the primary nic was deleted we get a 404 error.

## Expected behavior
Sync the nics of the server before and remove primary nic uuid when nic does not exist. 

#
## How to Reproduce

1. Create a IONOS server in Terraform with a nic.
2. Go into the dcd and remove the nic from the server. And provisions this new State.
3. Build plan / `Terraform refresh` will now throw a 404 Ressource not found. 

## Additional Notes

You can go around this problem with pulling the state. Removing the primary nic and pushing the state again.

I needed this because when changed the lan configuration and the lan could not be removed because of existing nics within the lan.

### PR DESCRIPTION
**Pull request by cristiGuranIonos**
… or apply

## What does this fix or implement?
fixes #467

## Checklist

- [ ] PR name added as appropriate (e.g. `feat:`/`fix:`/`doc:`/`test:`/`refactor:`)
- [ ] Tests added or updated
- [ ] Documentation updated
- [ ] Changelog updated and version incremented (label: upcoming release)
- [ ] Github Issue linked if any
- [ ] Jira task updated

### CODE REVIEW

File: ionoscloud/resource_server.go [hunk 1]
```diff
@@ -1556,14 +1556,32 @@ func setResourceServerData(ctx context.Context, client *ionoscloud.APIClient, d
...
+				return err
+			}
 		}
 		var nicEntry map[string]interface{}
 		var fwRulesEntries []map[string]interface{}
 
-		if nic.Properties != nil {
+		if nic != nil && nic.Properties != nil {
+			//fixes #467
+			if err := d.Set("primary_ip", (*nic.Properties.Ips)[0]); err != nil {
```
Comment (avirtopeanu-ionos) [inline ionoscloud/resource_server.go:1582]: iirc nics can be created with nil IPs too, is it possible that this could panic if `Ips` is nil/empty?

**Review by avirtopeanu-ionos — DISMISSED** [review]

File: ionoscloud/resource_server.go (hunk 1 above)
Comment (cristiGuranIonos) [reply ionoscloud/resource_server.go:1582]: good catch. will add a check
